language: cpp
os: linux
env:
  - BAZEL_VERSION=3.1.0
before_install:
  - chmod +x scripts/install.sh
  - scripts/install.sh
script:
  # build all targets in all subdirectories
  - bazel build ...
  # run all test
  - bazel test --test_output=all ...
